### ISSUE TITLE
[OTHER] bug 关闭正版验证 && 猎人指南针不指向逃生者解决方案

### ISSUE THREAD

**Issue by Night-Aurora** [Server-CT/ManiHunt#15]
1.关闭正版验证
io.ib67.manhunt.gui.vote
 InventoryClickEvent  
meta.getOwningPlayer() 在关闭正版验证后返回都是null
我的方法：
        vote(p, Objects.requireNonNull(Bukkit.getPlayer(meta.getOwner())));
2.猎人指南针不指向逃生者
io.ib67.manhunt.listener.Interact
其实不是不指向，而是点击的一瞬间指了一下，速度太快无法看清；
实测需要循环替换猎人手中的COMPASS才会持续指向逃生者

**Comment by iceBear67** [comment]
感谢反馈

**Comment by iceBear67** [comment]
游戏版本？

**Comment by Night-Aurora** [comment]
1.16.4

**Comment by iceBear67** [comment]
~~1.16.4屁事真多，好几个bug了~~  
如果条件允许，试着更换到1.16.1？v1.1大概在寒假初发布，开发者最近没什么时间

**Comment by iceBear67** [comment]
等会儿。
这好像不是bug反馈  
草，如果你已经解决了就当我上面没说吧

**Comment by iceBear67** [comment]
1.16.1 bukkitapi上还没有meta.getOwner，如果改了可能会导致兼容性炸开  
~~sbbukkit~~

**Comment by iceBear67** [comment]
@czm23333 要不要迁移到1.16.4?

**Comment by iceBear67** [comment]
> 1.16.1 bukkitapi上还没有meta.getOwner，如果改了可能会导致兼容性炸开
> ~sbbukkit~

貌似是被 deprecated 了

**Comment by iceBear67** [comment]
dcaa521d1aee18951823082bfef42d962ecb9dc1
