### ISSUE TITLE
[Feature]建议加一个是否开启开局自动传送的选择

### ISSUE THREAD

**Issue by gubaiovo** [Server-CT/ManiHunt#22]
**请问您的特性和什么问题有关吗?**
开局自动传送的功能
**描述一下您的建议...**
建议加一个是否开启开局自动传送的选择
**您考虑过的其他的想法...**
无
**附加内容...**
别传的太远、传海里？（（

**Comment by iceBear67** [comment]
已经加入
7f41c0a9db1fc313d3f89ae437463be5a99a174c
