### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by fengfeng16** [Server-CT/ManiHunt#27]
**请问您的特性和什么问题有关吗?**
死亡/获胜自动关服时间
**描述一下您的建议...**
建议把自动关服的时间加到配置中去，变成可以调控的
**您考虑过的其他的想法...**

**附加内容...**

**Comment by MossCG** [comment]
目前重置建议用bat自动删除地图文件，

**Comment by iceBear67** [comment]
PRs are welcome
